Repository electricitymaps/electricitymaps-contrib-rewrite, pull requests merged in 2023-01, with the labels that each got.

#176 Tvs/release candidate
  mobileapp/android/app/build.gradle
  mobileapp/ios/App/App.xcodeproj/project.pbxproj
  mobileapp/ios/App/Podfile
  web/.prettierignore
  web/config/exchanges.json
  web/config/excludedAggregatedExchanges.json
  web/config/world.json
  web/config/zones.json
  web/index.html
  web/pnpm-lock.yaml
  web/public/client-version.json
Labels: frontend 🎨, mobile app 📱

#177 stop replace all errors
  web/src/features/panels/zone/Attribution.tsx
  web/src/features/time/TimeAxis.tsx
Labels: frontend 🎨

#167 Remove unneeded fields from config files
  web/config/exchanges.json
  web/config/zones.json
  web/scripts/generate-zones-config.ts
Labels: frontend 🎨

#175 Replaces map with a fallback shown for users on old ios versions
  web/package.json
  web/src/features/map/MapFallback.tsx
  web/src/features/map/MapWrapper.tsx
Labels: frontend 🎨, dependencies

#178 comment out atom dev tools
  web/src/main.tsx
Labels: frontend 🎨

#180 Fix invalid href lang + add preconnects
  web/index.html
Labels: frontend 🎨

#179 include new tracking events
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.tsx
  web/src/features/map-controls/ConsumptionProductionToggle.tsx
  web/src/features/map-controls/SpatialAggregatesToggle.tsx
  web/src/features/time/TimeController.tsx
Labels: frontend 🎨, dependencies
